PDN-42: Reusable charts
pej-se/helm-charts pull request #1
Opened 2021-12-01 12:36 UTC by akowal

2021-12-01 12:54 UTC, nickjn92 requested changes

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/Chart.yaml
> +appVersion: "1.16.0"
start of with lower app version?

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +            - name: JAVA_TOOL_OPTIONS
This chart is a bit to tailored towards java applications at the moment, i think it can/should be generic enough to use it with i.e. frontend deployments and then this doesnt make sense. It can still work for java deployments if they put it in the normal `.Values.env` block

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +        prometheus.io/path: "/actuator/prometheus"
In line with other comments to make it a bit more generic, let these be configurable so it can be used from another context and the helm chart can supply sensible defaults that might be defaults thats tailored towards our java deployments

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +        prometheus.io/scrape: "true"
same as other comments about generic chart

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +      securityContext:
is there an option to leave it out completely, i know the frontend deployment had some problems with security context being present, could perhaps be solved by just changing the values though

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +            initialDelaySeconds: 15
make it configurable with some default

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +            initialDelaySeconds: 15
make it configurable with some default

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +              path: /actuator/health/liveness
make it configurable with some default

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +              path: /actuator/health/readiness
make it configurable with some default

2021-12-01 12:54 UTC, nickjn92 commented on charts/microservice/values.yaml
> +    memory: 256Mi
since we have lots of memory (compared to vcpus), should we allow defaults to be `512Mi` instead?  java apps gets a bit happier

2021-12-01 13:01 UTC, akowal commented on charts/microservice/templates/deployment.yaml
> +            - name: JAVA_TOOL_OPTIONS
Yes, that's the idea: reusable chart for JVM-based microservices to minimize copypasta. Making it non-JVM specific will lead to, again, copying a lot of duplicate values all over the place again: default resources, actuator probes, jvm opts, etc. Then there's no reason in having this chart at all, since it will be basically stripped down version of default chart created by `helm create`

2021-12-01 13:06 UTC, akowal commented on charts/microservice/values.yaml
> +    memory: 256Mi
I'm always glad to bump memory if it's available =) Done.

2021-12-01 13:07 UTC, akowal commented on charts/microservice/templates/deployment.yaml
> +            initialDelaySeconds: 15
For which of our services you want to have this value to be different?

2021-12-01 13:11 UTC, akowal commented on charts/microservice/Chart.yaml
> +appVersion: "1.16.0"
It's a default created by Helm and in fact we don't need it at all since it's useless, I removed it.

2021-12-01 13:24 UTC, akowal commented on charts/microservice/templates/deployment.yaml
> +        prometheus.io/path: "/actuator/prometheus"
For other types of apps, e.g. UI, I think it makes sense to create a separate reusable charts that will be specialized to their needs.

2021-12-01 13:24 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +            - name: JAVA_TOOL_OPTIONS
Of course there is, if this chart contains some defaults in the charts `values.yaml`. This allows us to reuse it for our JVM services without changing anything, but for other services like the status-screen-ui, they can change the small parts to fit their use case?

2021-12-01 13:25 UTC, akowal commented on charts/microservice/templates/deployment.yaml
> +        prometheus.io/scrape: "true"
I don't think it's possible to use templates like the port value if this is moved to the values file. Am I wrong?

2021-12-01 13:29 UTC, nickjn92 commented on charts/microservice/templates/_helpers.tpl
> +{{- define "microservice.name" -}}
I tried using this as a dependency, the name becomes `test-microservice`, which is not really what we want, it should only be `test`

2021-12-01 13:32 UTC, nickjn92 commented on charts/microservice/templates/_helpers.tpl
> +{{- define "microservice.labels" -}}
This generates
```
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
```
which is incorrect, version and name should come from the parent chart

2021-12-01 13:35 UTC, akowal commented on charts/microservice/templates/_helpers.tpl
> +{{- define "microservice.name" -}}
Did you forget to set `nameOverride`?

2021-12-01 13:35 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +      securityContext:
I tried setting it to `securityContext: {}` in the child chart, then it uses the parents default values :/

2021-12-01 13:41 UTC, nickjn92 commented on charts/microservice/templates/_helpers.tpl
> +{{- define "microservice.fullname" -}}
fullName resolves to `microservice-test`, it shouldnt be the case

2021-12-01 13:43 UTC, akowal commented on charts/microservice/templates/deployment.yaml
> +            - name: JAVA_TOOL_OPTIONS
But then every UI deployment will be copypasting the same duplicate "small parts" instead of creating a reusable charts for UI apps?

2021-12-01 13:44 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +        prometheus.io/scrape: "true"
eh? im not sure i follow

2021-12-01 13:44 UTC, nickjn92 commented on charts/microservice/templates/_helpers.tpl
> +{{- define "microservice.name" -}}
Why should i have to set `nameOverride`?

2021-12-01 13:51 UTC, nickjn92 commented on charts/microservice/templates/_helpers.tpl
> +{{- define "microservice.name" -}}
If you define the default to use `{{ .Release.Name }}` instead of `{{ .Chart.Name }}` i believe you get this expected behaviour

2021-12-01 13:52 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +            - name: JAVA_TOOL_OPTIONS
They dont have to create a whole new reusable chart, they can create a chart which uses this chart but sets their own defaults

2021-12-01 13:58 UTC, akowal commented on charts/microservice/templates/_helpers.tpl
> +{{- define "microservice.labels" -}}
What exactly is incorrect? Havin names overriden `helm template eu1dev organization` produces:
```
kind: Deployment
metadata:
  name: organization
  labels:
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: organization
    app.kubernetes.io/instance: eu1dev
    app.kubernetes.io/managed-by: Helm
```

which looks correct to me.

2021-12-01 14:01 UTC, akowal commented on charts/microservice/templates/_helpers.tpl
> +{{- define "microservice.fullname" -}}
That's the default behavior of generated template helpers if you don't set release name equal to the chart name and don't override full name. But since we use chart as a dependency we are expected to override its names.

2021-12-01 14:42 UTC, nickjn92 commented on charts/microservice/templates/deployment.yaml
> +        prometheus.io/scrape: "true"
I think you can it to work using blocks but thats ugly, e.g. `pod-annotations: |` and it will template the whole thing.

But since these are only limited to three, they could be something like
```
        prometheus.io/path: "{{ .Values.metrics.path }}"
        prometheus.io/scrape: "{{ .Values.metrics.scrape }}"
        prometheus.io/port: "{{ .Values.actuator.port }}"
```
Perhaps create a template helper to render the port as `.Values.metrics.port` if present otherwise default to `{{ .Values.actuator.port }}`,

2021-12-01 15:46 UTC, nickjn92 commented on charts/app/templates/deployment.yaml
> +        {{- if .Values.global.prometheus.enabled }}
cant se use set `prometheus.io/scrape: "true"` to `prometheus.io/scrape: {{ .Values.global.prometheus.enabled }}`? A bit less clutter in the yaml and we would see the annotations instead of them just being missing when inspecting the deployment

2021-12-01 15:50 UTC, akowal commented on charts/app/templates/deployment.yaml
> +        {{- if .Values.global.prometheus.enabled }}
I thought it's better not to add unnecessary annotations, otherwise path/port will have some default values which can be totally irrelevant to the app (e.g. UI app) and look confusing.

2021-12-01 15:51 UTC, nickjn92 commented on charts/app/templates/deployment.yaml
> +        {{- if .Values.global.prometheus.enabled }}
i guess but scrape would be set to false, anyways we can leave it as is then

2021-12-02 08:37 UTC, nickjn92 commented
I think its a good idea if we add linting and validation (files contain correct labels and best practices etc), i assume there be some github action for this already

2021-12-02 13:51 UTC, nickjn92 approved these changes

2021-12-02 13:55 UTC, merged